-- $Id$

--CONNECT TO <database>;

BIND @pwdsafe.lst BLOCKING ALL SQLERROR CONTINUE;

GRANT  EXECUTE ON PACKAGE AT24020.PWDADM TO USER DB2USER;
GRANT  EXECUTE ON PACKAGE AT24020.PWDADM TO USER DB2USER;
GRANT  EXECUTE ON PACKAGE AT24020.PWDADM TO USER DB2USER;

--CONNECT RESET;

--TERMINATE;