-- $Id$

--CONNECT TO <database>;

BIND @pwdsafeL.lst BLOCKING ALL SQLERROR CONTINUE;

GRANT  EXECUTE ON PACKAGE TESSUS.PWDADM TO USER DB2USER;
GRANT  EXECUTE ON PACKAGE TESSUS.PWDADM TO USER DB2USER;
GRANT  EXECUTE ON PACKAGE TESSUS.PWDADM TO USER DB2USER;

--CONNECT RESET;

--TERMINATE;