#! /bin/sh
#
# SCRIPT: embprep
# To prep and bind C embedded SQL programs
#
# Usage: embprep <prog_name> [ <db_name> [ <userid> <password> ]]

BITWIDTH=`LANG=C db2level | awk '/bits/{print $5}' | cut -b 2-3`
SUFFIX2=`uname -s | cut -b -1`
SUFFIX=$SUFFIX2$BITWIDTH

# Connect to a database.
if (test $# -lt 2)
then
   db2 connect to sample
elif (test $# -lt 3)
then
   db2 connect to $2
else
   db2 connect to $2 user $3 using $4
fi

# Precompile the program.
if [ -f $1".sqc" ]
then
  db2 prep $1.sqc bindfile using ${1}${SUFFIX}.bnd package using ${1}${SUFFIX} sqlerror continue validate run
  if [ -f utilemb.sqc ]
  then
    db2 prep utilemb.sqc bindfile using utilemb${SUFFIX}.bnd package using utilemb${SUFFIX}
  fi
fi

# Bind the program to the database.
db2 bind ${1}${SUFFIX}.bnd blocking all validate run
db2 bind utilemb${SUFFIX}.bnd

# Disconnect from the database.
db2 connect reset
db2 terminate
